"""empty message

Revision ID: 36654f9c5343
Revises: c7fb69e9cd76
Create Date: 2022-01-27 11:43:14.223611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36654f9c5343'
down_revision = 'c7fb69e9cd76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
